name: Lint

on:
  - push
  - pull_request

jobs:
  func:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        echo "HELLO"
        set -euxo pipefail
        python -m pip install --upgrade pip
        pip install tox
        sudo snap install --classic juju
        sudo lxd init --auto
        # This is a throw-away CI environment, do not do this at home
        sudo chmod 666 /var/snap/lxd/common/lxd/unix.socket
        # until Juju provides stable IPv6-support we unfortunately need this
        lxc network set lxdbr0 ipv6.address none
        juju bootstrap --no-gui --bootstrap-series jammy localhost
    - name: Bundle validation with tox using dry-run juju deploy
      run: tox -e lint
    - name: consider debugging
      uses: lhotari/action-upterm@v1
      if: failure()
